Module3 task1
htmlacademy-adaptive/2180451-mishka-27 pull request #4
Opened 2022-11-27 20:15 UTC by Dante01Rus

2022-11-28 13:14 UTC, pavel-nyukalo requested changes

2022-11-28 13:14 UTC, pavel-niukalo commented on source/less/catalog/product-catalog.less
> +  background: url("../../img/cart-icon.svg") no-repeat center;
Вот тут опасно с автоподстановкой путей. Все препроцессорные файлы у нас потом собираются и кладутся в `css/style.css`. Вот относительно этого файла и нужно подниматься. То есть тут как и на первом курсе - `url("../img/...")`

2022-11-28 13:14 UTC, pavel-niukalo commented on source/less/page__body.less
> +.page__body {
`page__body` - элемент блока `page`. Так что вот эти стили в `page.less` и описываем. А этот файл удалим. Шрифты можно в отдельный файл вынести - `fonts.less`

2022-11-28 13:14 UTC, pavel-niukalo commented on source/less/style.less
> +@import "user-list.less";
К этому могут придраться на защите сославшись на данный [критерий](https://up.htmlacademy.ru/adaptive/27/criteries#b13)

![image](https://user-images.githubusercontent.com/52506235/204286574-d8f172d5-4ed0-42c0-806d-77f422595b3a.png)

2022-11-29 06:57 UTC, Dante01Rus commented
исправил

2022-11-30 07:43 UTC, pavel-nyukalo approved these changes

2022-11-30 07:43 UTC, merged