Module4 task1
htmlacademy-adaptive/2180451-mishka-27 pull request #5
Opened 2022-12-04 10:46 UTC by Dante01Rus

резиновая верстка всех страниц

2022-12-04 13:46 UTC, pavel-nyukalo requested changes

2022-12-04 13:46 UTC, pavel-nyukalo commented on source/catalog.html
> +      <div class="intro-inner__free-delivery">Бесплатная доставка по России</div>
Я бы сделал через `p`, текстовый элемент

2022-12-04 13:46 UTC, pavel-nyukalo commented on source/less/form/filters.less
> +  background: url("../../img/phone-icon.svg") no-repeat right 7px center;
Пути - нам от `style.css` нужно будет выйти один раз

2022-12-04 13:46 UTC, pavel-nyukalo commented on source/less/general/page.less
> +    max-width: 1150px;
В целом все выглядит хорошо, единственное - ограничивать не стоит по ширине, ибо у нас есть фоны, которые должны тянуться на всю ширину экрана. Например, вот этот серый фон футера

![image](https://user-images.githubusercontent.com/52506235/205493841-51769bc2-a220-43ce-b3e9-15655df05cc5.png)

То есть открыв сайт на экране больше, чем 1150px, этот серый цвет должен растягиваться на всю ширину

![image](https://user-images.githubusercontent.com/52506235/205493889-d856a0a1-13fc-4c94-9c40-6ef83fe4ff71.png)

2022-12-04 13:46 UTC, pavel-nyukalo commented on source/less/index/intro-main.less
> +}
Пропишу здесь, но относится ко всему. И в целом ошибкой не является, но все стили, которые не меняются от разрешения к разрешению можно не дублировать - они все равно применятся к блоку.

Например вот здесь:

![image](https://user-images.githubusercontent.com/52506235/205494033-a1d5b9b7-cb2e-4a63-8711-90db0aaf4d91.png)

Как видно, все стили от планшета применяются, а потом переопределяются в десктопе. А тут они 1:1, то есть тут можно вообще оставить так
```less
.intro-main__zigzag-line {
  @media (min-width: @tablet-width) {
    position: absolute;
    display: block;
    left: -50px;
    bottom: -17px;
    height: 34px;
    width: calc(100% + 100px);
    background-image: url("../../img/zigzag-fill-tablet.svg");
    background-repeat: repeat-x;
    z-index: 2;
  }
}
```

И все будет работать так же как и сейчас

Можно оставить и как сейчас у тебя, это не ошибка, но можно сократить код в разы

2022-12-04 15:29 UTC, Dante01Rus commented on source/less/general/page.less
> +    max-width: 1150px;
не совсем понял этот момент. заливка футера тянется вместе с ним, за пределами страницы это же область тега html. Max-width 1150px прописал, чтобы сайт нормально выглядел и центрировался.

2022-12-05 09:29 UTC, pavel-niukalo approved these changes

2022-12-05 09:29 UTC, merged